version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: agent-postgres
    environment:
      POSTGRES_DB: agentmiddleware
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: AgentMiddleware.Server/Dockerfile
    container_name: agent-server
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=agentmiddleware;Username=postgres;Password=devpassword123
      - Azure__ProjectEndpoint=${AZURE_PROJECT_ENDPOINT}
      - Azure__ModelDeployment=${AZURE_MODEL_DEPLOYMENT}
      - AzureAd__TenantId=${AZURE_AD_TENANT_ID}
      - AzureAd__ClientId=${AZURE_AD_CLIENT_ID}
      - AzureAd__Audience=${AZURE_AD_AUDIENCE}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
